//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_Malaria
    {
        public int About_Malaria_ID { get; set; }
        public string Malaria_Description { get; set; }
    }
}
