//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malaria_Risk_Zone
    {
        public int Malaria_Risk_Zone_ID { get; set; }
        public string Risk_Zone_Location { get; set; }
        public string Risk_Zone { get; set; }
        public string Severity { get; set; }
    }
}
