//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int Publication_ID { get; set; }
        public string Publication_Description { get; set; }
        public string Publication_Link { get; set; }
    }
}
