//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Statistic_ID { get; set; }
        public string Malaria_Case { get; set; }
        public string Malaria_Incidence { get; set; }
        public string Malaria_Mortality_Percentage { get; set; }
    }
}
