//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom_Sign
    {
        public int Symptom_Sign_ID { get; set; }
        public string Symptom_Name { get; set; }
        public string Symptom_Description { get; set; }
        public string Sign_Name { get; set; }
        public string Sign_Description { get; set; }
    }
}
